/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvitationsRouteRouteImport } from './routes/invitations/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as DashboardWorkspaceIdRouteRouteImport } from './routes/dashboard/$workspaceId/route'
import { Route as InvitationsTokenIndexRouteImport } from './routes/invitations/$token/index'
import { Route as DashboardWorkspaceIdIndexRouteImport } from './routes/dashboard/$workspaceId/index'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/auth/verify-email/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DashboardWorkspaceIdTrashIndexRouteImport } from './routes/dashboard/$workspaceId/trash/index'
import { Route as DashboardWorkspaceIdSettingsIndexRouteImport } from './routes/dashboard/$workspaceId/settings/index'
import { Route as DashboardWorkspaceIdSearchIndexRouteImport } from './routes/dashboard/$workspaceId/search/index'
import { Route as DashboardWorkspaceIdProcessingIndexRouteImport } from './routes/dashboard/$workspaceId/processing/index'
import { Route as DashboardWorkspaceIdPlansIndexRouteImport } from './routes/dashboard/$workspaceId/plans/index'
import { Route as DashboardWorkspaceIdMembersIndexRouteImport } from './routes/dashboard/$workspaceId/members/index'
import { Route as DashboardWorkspaceIdLabelsIndexRouteImport } from './routes/dashboard/$workspaceId/labels/index'
import { Route as DashboardWorkspaceIdDriveIndexRouteImport } from './routes/dashboard/$workspaceId/drive/index'
import { Route as DashboardWorkspaceIdActivityIndexRouteImport } from './routes/dashboard/$workspaceId/activity/index'

const InvitationsRouteRoute = InvitationsRouteRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspaceIdRouteRoute =
  DashboardWorkspaceIdRouteRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const InvitationsTokenIndexRoute = InvitationsTokenIndexRouteImport.update({
  id: '/$token/',
  path: '/$token/',
  getParentRoute: () => InvitationsRouteRoute,
} as any)
const DashboardWorkspaceIdIndexRoute =
  DashboardWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardWorkspaceIdTrashIndexRoute =
  DashboardWorkspaceIdTrashIndexRouteImport.update({
    id: '/trash/',
    path: '/trash/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdSettingsIndexRoute =
  DashboardWorkspaceIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdSearchIndexRoute =
  DashboardWorkspaceIdSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdProcessingIndexRoute =
  DashboardWorkspaceIdProcessingIndexRouteImport.update({
    id: '/processing/',
    path: '/processing/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdPlansIndexRoute =
  DashboardWorkspaceIdPlansIndexRouteImport.update({
    id: '/plans/',
    path: '/plans/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdMembersIndexRoute =
  DashboardWorkspaceIdMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdLabelsIndexRoute =
  DashboardWorkspaceIdLabelsIndexRouteImport.update({
    id: '/labels/',
    path: '/labels/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdDriveIndexRoute =
  DashboardWorkspaceIdDriveIndexRouteImport.update({
    id: '/drive/',
    path: '/drive/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)
const DashboardWorkspaceIdActivityIndexRoute =
  DashboardWorkspaceIdActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => DashboardWorkspaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/invitations': typeof InvitationsRouteRouteWithChildren
  '/dashboard/$workspaceId': typeof DashboardWorkspaceIdRouteRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/dashboard/$workspaceId/': typeof DashboardWorkspaceIdIndexRoute
  '/invitations/$token/': typeof InvitationsTokenIndexRoute
  '/dashboard/$workspaceId/activity/': typeof DashboardWorkspaceIdActivityIndexRoute
  '/dashboard/$workspaceId/drive/': typeof DashboardWorkspaceIdDriveIndexRoute
  '/dashboard/$workspaceId/labels/': typeof DashboardWorkspaceIdLabelsIndexRoute
  '/dashboard/$workspaceId/members/': typeof DashboardWorkspaceIdMembersIndexRoute
  '/dashboard/$workspaceId/plans/': typeof DashboardWorkspaceIdPlansIndexRoute
  '/dashboard/$workspaceId/processing/': typeof DashboardWorkspaceIdProcessingIndexRoute
  '/dashboard/$workspaceId/search/': typeof DashboardWorkspaceIdSearchIndexRoute
  '/dashboard/$workspaceId/settings/': typeof DashboardWorkspaceIdSettingsIndexRoute
  '/dashboard/$workspaceId/trash/': typeof DashboardWorkspaceIdTrashIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/invitations': typeof InvitationsRouteRouteWithChildren
  '/about': typeof AboutIndexRoute
  '/contact': typeof ContactIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/dashboard/$workspaceId': typeof DashboardWorkspaceIdIndexRoute
  '/invitations/$token': typeof InvitationsTokenIndexRoute
  '/dashboard/$workspaceId/activity': typeof DashboardWorkspaceIdActivityIndexRoute
  '/dashboard/$workspaceId/drive': typeof DashboardWorkspaceIdDriveIndexRoute
  '/dashboard/$workspaceId/labels': typeof DashboardWorkspaceIdLabelsIndexRoute
  '/dashboard/$workspaceId/members': typeof DashboardWorkspaceIdMembersIndexRoute
  '/dashboard/$workspaceId/plans': typeof DashboardWorkspaceIdPlansIndexRoute
  '/dashboard/$workspaceId/processing': typeof DashboardWorkspaceIdProcessingIndexRoute
  '/dashboard/$workspaceId/search': typeof DashboardWorkspaceIdSearchIndexRoute
  '/dashboard/$workspaceId/settings': typeof DashboardWorkspaceIdSettingsIndexRoute
  '/dashboard/$workspaceId/trash': typeof DashboardWorkspaceIdTrashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/invitations': typeof InvitationsRouteRouteWithChildren
  '/dashboard/$workspaceId': typeof DashboardWorkspaceIdRouteRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/dashboard/$workspaceId/': typeof DashboardWorkspaceIdIndexRoute
  '/invitations/$token/': typeof InvitationsTokenIndexRoute
  '/dashboard/$workspaceId/activity/': typeof DashboardWorkspaceIdActivityIndexRoute
  '/dashboard/$workspaceId/drive/': typeof DashboardWorkspaceIdDriveIndexRoute
  '/dashboard/$workspaceId/labels/': typeof DashboardWorkspaceIdLabelsIndexRoute
  '/dashboard/$workspaceId/members/': typeof DashboardWorkspaceIdMembersIndexRoute
  '/dashboard/$workspaceId/plans/': typeof DashboardWorkspaceIdPlansIndexRoute
  '/dashboard/$workspaceId/processing/': typeof DashboardWorkspaceIdProcessingIndexRoute
  '/dashboard/$workspaceId/search/': typeof DashboardWorkspaceIdSearchIndexRoute
  '/dashboard/$workspaceId/settings/': typeof DashboardWorkspaceIdSettingsIndexRoute
  '/dashboard/$workspaceId/trash/': typeof DashboardWorkspaceIdTrashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/invitations'
    | '/dashboard/$workspaceId'
    | '/about/'
    | '/contact/'
    | '/workspaces/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/verify-email/'
    | '/dashboard/$workspaceId/'
    | '/invitations/$token/'
    | '/dashboard/$workspaceId/activity/'
    | '/dashboard/$workspaceId/drive/'
    | '/dashboard/$workspaceId/labels/'
    | '/dashboard/$workspaceId/members/'
    | '/dashboard/$workspaceId/plans/'
    | '/dashboard/$workspaceId/processing/'
    | '/dashboard/$workspaceId/search/'
    | '/dashboard/$workspaceId/settings/'
    | '/dashboard/$workspaceId/trash/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/invitations'
    | '/about'
    | '/contact'
    | '/workspaces'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify-email'
    | '/dashboard/$workspaceId'
    | '/invitations/$token'
    | '/dashboard/$workspaceId/activity'
    | '/dashboard/$workspaceId/drive'
    | '/dashboard/$workspaceId/labels'
    | '/dashboard/$workspaceId/members'
    | '/dashboard/$workspaceId/plans'
    | '/dashboard/$workspaceId/processing'
    | '/dashboard/$workspaceId/search'
    | '/dashboard/$workspaceId/settings'
    | '/dashboard/$workspaceId/trash'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/invitations'
    | '/dashboard/$workspaceId'
    | '/about/'
    | '/contact/'
    | '/workspaces/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/verify-email/'
    | '/dashboard/$workspaceId/'
    | '/invitations/$token/'
    | '/dashboard/$workspaceId/activity/'
    | '/dashboard/$workspaceId/drive/'
    | '/dashboard/$workspaceId/labels/'
    | '/dashboard/$workspaceId/members/'
    | '/dashboard/$workspaceId/plans/'
    | '/dashboard/$workspaceId/processing/'
    | '/dashboard/$workspaceId/search/'
    | '/dashboard/$workspaceId/settings/'
    | '/dashboard/$workspaceId/trash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  InvitationsRouteRoute: typeof InvitationsRouteRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$workspaceId': {
      id: '/dashboard/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/dashboard/$workspaceId'
      preLoaderRoute: typeof DashboardWorkspaceIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/invitations/$token/': {
      id: '/invitations/$token/'
      path: '/$token'
      fullPath: '/invitations/$token/'
      preLoaderRoute: typeof InvitationsTokenIndexRouteImport
      parentRoute: typeof InvitationsRouteRoute
    }
    '/dashboard/$workspaceId/': {
      id: '/dashboard/$workspaceId/'
      path: '/'
      fullPath: '/dashboard/$workspaceId/'
      preLoaderRoute: typeof DashboardWorkspaceIdIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/verify-email'
      fullPath: '/auth/verify-email/'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/$workspaceId/trash/': {
      id: '/dashboard/$workspaceId/trash/'
      path: '/trash'
      fullPath: '/dashboard/$workspaceId/trash/'
      preLoaderRoute: typeof DashboardWorkspaceIdTrashIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/settings/': {
      id: '/dashboard/$workspaceId/settings/'
      path: '/settings'
      fullPath: '/dashboard/$workspaceId/settings/'
      preLoaderRoute: typeof DashboardWorkspaceIdSettingsIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/search/': {
      id: '/dashboard/$workspaceId/search/'
      path: '/search'
      fullPath: '/dashboard/$workspaceId/search/'
      preLoaderRoute: typeof DashboardWorkspaceIdSearchIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/processing/': {
      id: '/dashboard/$workspaceId/processing/'
      path: '/processing'
      fullPath: '/dashboard/$workspaceId/processing/'
      preLoaderRoute: typeof DashboardWorkspaceIdProcessingIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/plans/': {
      id: '/dashboard/$workspaceId/plans/'
      path: '/plans'
      fullPath: '/dashboard/$workspaceId/plans/'
      preLoaderRoute: typeof DashboardWorkspaceIdPlansIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/members/': {
      id: '/dashboard/$workspaceId/members/'
      path: '/members'
      fullPath: '/dashboard/$workspaceId/members/'
      preLoaderRoute: typeof DashboardWorkspaceIdMembersIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/labels/': {
      id: '/dashboard/$workspaceId/labels/'
      path: '/labels'
      fullPath: '/dashboard/$workspaceId/labels/'
      preLoaderRoute: typeof DashboardWorkspaceIdLabelsIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/drive/': {
      id: '/dashboard/$workspaceId/drive/'
      path: '/drive'
      fullPath: '/dashboard/$workspaceId/drive/'
      preLoaderRoute: typeof DashboardWorkspaceIdDriveIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
    '/dashboard/$workspaceId/activity/': {
      id: '/dashboard/$workspaceId/activity/'
      path: '/activity'
      fullPath: '/dashboard/$workspaceId/activity/'
      preLoaderRoute: typeof DashboardWorkspaceIdActivityIndexRouteImport
      parentRoute: typeof DashboardWorkspaceIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardWorkspaceIdRouteRouteChildren {
  DashboardWorkspaceIdIndexRoute: typeof DashboardWorkspaceIdIndexRoute
  DashboardWorkspaceIdActivityIndexRoute: typeof DashboardWorkspaceIdActivityIndexRoute
  DashboardWorkspaceIdDriveIndexRoute: typeof DashboardWorkspaceIdDriveIndexRoute
  DashboardWorkspaceIdLabelsIndexRoute: typeof DashboardWorkspaceIdLabelsIndexRoute
  DashboardWorkspaceIdMembersIndexRoute: typeof DashboardWorkspaceIdMembersIndexRoute
  DashboardWorkspaceIdPlansIndexRoute: typeof DashboardWorkspaceIdPlansIndexRoute
  DashboardWorkspaceIdProcessingIndexRoute: typeof DashboardWorkspaceIdProcessingIndexRoute
  DashboardWorkspaceIdSearchIndexRoute: typeof DashboardWorkspaceIdSearchIndexRoute
  DashboardWorkspaceIdSettingsIndexRoute: typeof DashboardWorkspaceIdSettingsIndexRoute
  DashboardWorkspaceIdTrashIndexRoute: typeof DashboardWorkspaceIdTrashIndexRoute
}

const DashboardWorkspaceIdRouteRouteChildren: DashboardWorkspaceIdRouteRouteChildren =
  {
    DashboardWorkspaceIdIndexRoute: DashboardWorkspaceIdIndexRoute,
    DashboardWorkspaceIdActivityIndexRoute:
      DashboardWorkspaceIdActivityIndexRoute,
    DashboardWorkspaceIdDriveIndexRoute: DashboardWorkspaceIdDriveIndexRoute,
    DashboardWorkspaceIdLabelsIndexRoute: DashboardWorkspaceIdLabelsIndexRoute,
    DashboardWorkspaceIdMembersIndexRoute:
      DashboardWorkspaceIdMembersIndexRoute,
    DashboardWorkspaceIdPlansIndexRoute: DashboardWorkspaceIdPlansIndexRoute,
    DashboardWorkspaceIdProcessingIndexRoute:
      DashboardWorkspaceIdProcessingIndexRoute,
    DashboardWorkspaceIdSearchIndexRoute: DashboardWorkspaceIdSearchIndexRoute,
    DashboardWorkspaceIdSettingsIndexRoute:
      DashboardWorkspaceIdSettingsIndexRoute,
    DashboardWorkspaceIdTrashIndexRoute: DashboardWorkspaceIdTrashIndexRoute,
  }

const DashboardWorkspaceIdRouteRouteWithChildren =
  DashboardWorkspaceIdRouteRoute._addFileChildren(
    DashboardWorkspaceIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardWorkspaceIdRouteRoute: typeof DashboardWorkspaceIdRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardWorkspaceIdRouteRoute: DashboardWorkspaceIdRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface InvitationsRouteRouteChildren {
  InvitationsTokenIndexRoute: typeof InvitationsTokenIndexRoute
}

const InvitationsRouteRouteChildren: InvitationsRouteRouteChildren = {
  InvitationsTokenIndexRoute: InvitationsTokenIndexRoute,
}

const InvitationsRouteRouteWithChildren =
  InvitationsRouteRoute._addFileChildren(InvitationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  InvitationsRouteRoute: InvitationsRouteRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
